/* Generated by scripts/generate-math-cases.py; do not edit.
 * Corpus SHA256: e4afdd516e38dbc4824afd4f730cce18969d9ef08a72f39d3fbb04e9ae0f4ac7 */
#pragma once
#include <stdbool.h>
typedef struct { const char *source; bool display, fallback; } math_case_t;
static const math_case_t math_cases[] = {
    {"x_i", false, false},
    {"\\alpha", false, false},
    {"\\mathbb{R}", false, false},
    {"a^2+b^2=c^2", false, false},
    {"x_{i,j}^{(k)}", false, false},
    {"\\sum_{i=1}^{n} x_i", false, false},
    {"\\int_0^1 x^2\\,dx", false, false},
    {"\\alpha+\\beta\\leq\\gamma", false, false},
    {"\\forall x\\in\\mathbb{R}", false, false},
    {"\\nabla f(x)", false, false},
    {"\\infty", false, false},
    {"\\partial f/\\partial x", false, false},
    {"\\frac{1}{1+\\frac{1}{x}}", false, false},
    {"\\sqrt{x^2+y^2}", false, false},
    {"\\sqrt[3]{8}", false, false},
    {"\\text{subject to}", false, false},
    {"\\mathrm{kg}", false, false},
    {"\\mathbf{x}", false, false},
    {"\\mathcal{L}", false, false},
    {"\\mathbb{R}", false, false},
    {" x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a} ", true, false},
    {" \\left(\\frac{x+1}{x-1}\\right)^2 +\\left\\lVert \\mathbf{x}\\right\\rVert_2 ", true, false},
    {" A=\\begin{pmatrix} 1 & 2 \\\\ 3 & 4 \\end{pmatrix} ", true, false},
    {" \\begin{aligned} \\min_{\\mathbf{x}}\\quad & \\mathbf{c}^{T}\\mathbf{x}\\\\ \\text{subject to}\\quad & A\\mathbf{x}\\leq\\mathbf{b}\\\\ & \\mathbf{x}\\geq 0 \\end{aligned} ", true, false},
    {" f(x)=\\begin{cases} x^2 & x\\geq 0\\\\ -x & x<0 \\end{cases} ", true, false},
    {" \\lim_{n\\to\\infty}\\frac{1}{n}\\sum_{i=1}^{n} f(i/n) =\\int_0^1 f(x)\\,dx ", true, false},
    {" \\inkpyUnknownCommand{x} ", true, true},
    {" \\frac{1}{x ", true, true},
    {" a_1+a_2+a_3+a_4+a_5+a_6+a_7+a_8+a_9+a_{10}+a_{11}+a_{12}+a_{13}+a_{14}+a_{15} ", true, true},
};
