#pragma once
/* X4 Pro only. Source/revision and licence: docs/PORTING.md. */
enum {
    PIN_RAIL = 1, PIN_TOUCH_ENABLE = 2, PIN_POWER = 3, PIN_TOUCH_RESET = 4,
    PIN_SD_ENABLE = 5, PIN_EPD_BUSY = 6, PIN_NEXT = 7,
    PIN_COOL = 8, PIN_WARM = 9, PIN_TOUCH_IRQ = 10,
    PIN_EPD_MOSI = 11, PIN_EPD_CLK = 12, PIN_EPD_CS = 13,
    PIN_EPD_RESET = 14, PIN_EPD_DC = 18, PIN_CHARGING = 21,
    PIN_I2C_SCL = 38, PIN_I2C_SDA = 39, PIN_SD_D0 = 40,
    PIN_SD_CLK = 41, PIN_SD_CMD = 42, PIN_PREV = 0,
    PANEL_WIDTH = 800, PANEL_HEIGHT = 480,
    PANEL_STRIDE = PANEL_WIDTH / 8, PANEL_BYTES = PANEL_STRIDE * PANEL_HEIGHT
};
