"""Run after the host probe. Keep one generated snapshot for cross-builds."""
import csv
import hashlib
import json
from pathlib import Path
root = Path(__file__).resolve().parent.parent
results = root / 'prototypes/math/build'
rows = list(csv.DictReader((results / 'results.tsv').open(), delimiter='\t'))
if len(rows) != 29 or sum(r['status'] == 'rendered' for r in rows) != 26:
    raise SystemExit('Require a complete, passing 29-case host run')
digest = hashlib.sha256((root / 'fixtures/markdown-math.md').read_bytes()).hexdigest()
lines = ['/* Generated by scripts/generate-math-cases.py; do not edit.',
         f' * Corpus SHA256: {digest} */', '#pragma once', '#include <stdbool.h>',
         'typedef struct { const char *source; bool display, fallback; } math_case_t;',
         'static const math_case_t math_cases[] = {']
for row in rows:
    source = (results / 'results' / (row['id'] + '.tex')).read_text()
    lines.append('    {%s, %s, %s},' % (json.dumps(source), str(row['style']=='display').lower(),
                                    str(row['status']=='fallback').lower()))
lines.append('};')
(root / 'main/math_cases.h').write_text('\n'.join(lines) + '\n')
